AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy a service on AWS Fargate, hosted in a private subnet
Parameters:
  InfrastructureStackName:
    Type: String
    Default: av-infrastructure
    Description:
      The name of the parent Fargate networking stack that you created. Necessary
      to locate and reference resources created by that stack.
  AdapterStackName:
    Type: String
    Default: av-adapter
    Description: The name of the Adapter stack that you created. Necessary
      to locate and reference resources created by that stack.
  ImageRepoName:
    Type: String
    Default: codemill-docker.jfrog.io/accurate-player/accurate-video-jobs
    Description: The docker image repo to use for image deployment
  ImageTag:
    Type: String
    Default: 4.6.1
    Description: The docker image tag to use for image deployment
  RegistryCredentials:
    Type: String
    Description: Credentials to codemill.jfrog.io for pulling docker images
  ContainerCpu:
    Type: Number
    Default: 512
    Description: How much CPU to give the container. 1024 is 1 CPU
  ContainerMemory:
    Type: Number
    Default: 1024
    Description: How much memory in megabytes to give the container
  DesiredCount:
    Type: Number
    Default: 2
    Description: How many copies of the service task to run
  ApplicationTag:
    Type: String
    Default: "accurate-video"
    Description: Used to tag all resources
  BlackFrameLocation:
    Type: String
    Default: "s3://av-black-frame-codemill/black25.mp4"
    Description: Black frame file used
  BlackFrameDuration:
    Type: String
    Default: "1200"
    Description: Black frame duration
  BlackFrameNumerator:
    Type: String
    Default: "25"
    Description: Black frame numerator
  BlackFrameDenominator:
    Type: String
    Default: "1"
    Description: Black frame denominator
  PrivateSubnetOne:
    Description: "Private Subnet One ID"
    Type: AWS::EC2::Subnet::Id
  PrivateSubnetTwo:
    Description: "Private Subnet Two ID"
    Type: AWS::EC2::Subnet::Id
  ClusterName:
    Description: "ECS cluster name"
    Type: String
    Default: av-cluster
  VpcCidrBlock:
    Type: String
    Description: VPC CIDR Block (e.g. 10.0.0.0/16)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Service configuration"
        Parameters:
          - ContainerCpu
          - ContainerMemory
          - DesiredCount
      - Label:
          default: "Image configuration"
        Parameters:
          - ImageRepoName
          - ImageTag
          - RegistryCredentials
      - Label:
          default: "Elemental configuration"
        Parameters:
          - BlackFrameLocation
          - BlackFrameDuration
          - BlackFrameNumerator
          - BlackFrameDenominator
      - Label:
          default: "Other"
        Parameters:
          - InfrastructureStackName
          - AdapterStackName
          - ApplicationTag

Resources:
  # The task definition. This is a simple metadata description of what
  # container to run, and what resource requirements it has.
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: av-jobs
      Cpu: !Ref "ContainerCpu"
      Memory: !Ref "ContainerMemory"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: av-jobs
          Cpu: !Ref "ContainerCpu"
          Memory: !Ref "ContainerMemory"
          Image: !Sub ${ImageRepoName}:${ImageTag}
          RepositoryCredentials:
            CredentialsParameter: !Ref "RegistryCredentials"
          PortMappings:
            - ContainerPort: 5701
            - ContainerPort: 5699
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group:
                Fn::ImportValue: !Sub ${InfrastructureStackName}:AVLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: av-jobs
          Environment:
            - Name: QUARKUS_VERTX_CLUSTER_HOST
              Value: "0.0.0.0"
            - Name: QUARKUS_VERTX_CLUSTER_PORT
              Value: 5699
            - Name: QUARKUS_VERTX_CLUSTER_PUBLIC_PORT
              Value: 5699
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: HZE_CLUSTER_NAME_REGEXP
              Value: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster\/${ClusterName}
            - Name: HZE_SERVICE_NAME_REGEXP
              Value: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service\/${ClusterName}\/[a-zA-z0-9].*-(JobsService|AdapterService)-.*[a-zA-z0-9]
            - Name: HZE_IPV4_CIDR
              Value: !Ref VpcCidrBlock
            - Name: AV_RUNNER_LOWRES_TEMPLATE_ID
              Value: !Ref MediaConvertPresetStandardH264
            - Name: AV_RUNNER_AUDIO_EXTRACT_TEMPLATE_ID
              Value: !Ref MediaConvertPresetWav
            - Name: AV_RUNNER_BLACK_FRAME_LOCATION
              Value: !Ref BlackFrameLocation
            - Name: AV_RUNNER_BLACK_FRAME_DURATION
              Value: !Ref BlackFrameDuration
            - Name: AV_RUNNER_BLACK_FRAME_NUMERATOR
              Value: !Ref BlackFrameNumerator
            - Name: AV_RUNNER_BLACK_FRAME_DENOMINATOR
              Value: !Ref BlackFrameDenominator
            - Name: AV_RUNNER_EXECUTOR_POLL_INTERVAL
              Value: PT1M
            - Name: AP_ADAPTER_URL_MP_REST_URL
              Value: !Sub
                - "http://${AdapterServiceName}.av.local:8080"
                - AdapterServiceName:
                    Fn::ImportValue: !Sub ${AdapterStackName}:DiscoveryServiceName
            - Name: AV_RUNNER_BINDIR
              Value: /usr/local/bin
            - Name: CLUSTER_XML
              Value: "/opt/ecs-cluster.xml"
          Secrets:
            - Name: AP_ADAPTER_USERNAME
              ValueFrom: !Sub
                - "${AuthRunnerSecretArn}:username::"
                - AuthRunnerSecretArn:
                    Fn::ImportValue: !Sub ${AdapterStackName}:AuthRunnerSecretArn
            - Name: AP_ADAPTER_PASSWORD
              ValueFrom: !Sub
                - "${AuthRunnerSecretArn}:password::"
                - AuthRunnerSecretArn:
                    Fn::ImportValue: !Sub ${AdapterStackName}:AuthRunnerSecretArn
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  # This is a role which is used by the ECS tasks themselves.
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: [sts:AssumeRole]
      Path: /
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource:
                  - !Ref RegistryCredentials
                  - Fn::ImportValue: !Sub ${AdapterStackName}:AuthRunnerSecretArn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: [sts:AssumeRole]
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElementalMediaConvertFullAccess
      Policies:
        - PolicyName: AmazonECSTaskRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:HeadObject
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ecs:ListClusters"
                  - "ecs:ListServices"
                  - "ecs:ListTasks"
                  - "ecs:DescribeTasks"
                Resource: "*"
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  DiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: Discovery Service for the Demo Application
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
          - TTL: 60
            Type: SRV
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: av-jobs
      NamespaceId:
        Fn::ImportValue: !Sub ${InfrastructureStackName}:PrivateDNSNamespace
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  # The service. The service is a resource which allows you to run multiple
  # copies of a type of task, and gather up their logs and metrics, as well
  # as monitor the number of running tasks and replace any that have crashed
  JobsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: !Ref "DesiredCount"
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn
          Port: 5699
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - Fn::ImportValue: !Sub ${InfrastructureStackName}:AvJobsSG
          Subnets:
            - !Ref PrivateSubnetOne
            - !Ref PrivateSubnetTwo
      PlatformVersion: "1.4.0"
      TaskDefinition: !Ref "TaskDefinition"
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  MediaConvertPresetStandardH264:
    Type: AWS::MediaConvert::Preset
    Properties:
      Description: Generated by Accurate Video
      Name: accurate_video_standard_h264_follow
      SettingsJson:
        VideoDescription:
          Width: 1920
          ScalingBehavior: DEFAULT
          Height: 1080
          VideoPreprocessors:
            Deinterlacer:
              Algorithm: INTERPOLATE
              Mode: DEINTERLACE
              Control: NORMAL
          TimecodeInsertion: DISABLED
          AntiAlias: ENABLED
          Sharpness: 50
          CodecSettings:
            Codec: H_264
            H264Settings:
              InterlaceMode: PROGRESSIVE
              ParNumerator: 1
              NumberReferenceFrames: 3
              Syntax: DEFAULT
              FramerateDenominator: 1
              GopClosedCadence: 1
              HrdBufferInitialFillPercentage: 90
              GopSize: 90
              Slices: 1
              GopBReference: DISABLED
              HrdBufferSize: 12750000
              SlowPal: DISABLED
              ParDenominator: 1
              SpatialAdaptiveQuantization: ENABLED
              TemporalAdaptiveQuantization: ENABLED
              FlickerAdaptiveQuantization: DISABLED
              EntropyEncoding: CABAC
              Bitrate: 2000000
              FramerateControl: INITIALIZE_FROM_SOURCE
              RateControlMode: CBR
              CodecProfile: HIGH
              Telecine: NONE
              FramerateNumerator: 25
              MinIInterval: 0
              AdaptiveQuantization: HIGH
              CodecLevel: LEVEL_4
              FieldEncoding: PAFF
              SceneChangeDetect: ENABLED
              QualityTuningLevel: MULTI_PASS_HQ
              FramerateConversionAlgorithm: DUPLICATE_DROP
              UnregisteredSeiTimecode: DISABLED
              GopSizeUnits: FRAMES
              ParControl: SPECIFIED
              NumberBFramesBetweenReferenceFrames: 1
              RepeatPps: DISABLED
          AfdSignaling: NONE
          DropFrameTimecode: ENABLED
          RespondToAfd: NONE
          ColorMetadata: INSERT
        AudioDescriptions:
          - AudioTypeControl: FOLLOW_INPUT
            AudioSourceName: Audio Selector 1
            CodecSettings:
              Codec: AAC
              AacSettings:
                AudioDescriptionBroadcasterMix: NORMAL
                Bitrate: 128000
                RateControlMode: CBR
                CodecProfile: LC
                CodingMode: CODING_MODE_2_0
                RawFormat: NONE
                SampleRate: 48000
                Specification: MPEG4
            LanguageCodeControl: FOLLOW_INPUT
            AudioType: 0
        ContainerSettings:
          Container: MP4
          Mp4Settings:
            CslgAtom: INCLUDE
            FreeSpaceBox: EXCLUDE
            MoovPlacement: PROGRESSIVE_DOWNLOAD

  MediaConvertPresetWav:
    Type: AWS::MediaConvert::Preset
    Properties:
      Description: Generated by Accurate Video
      Name: accurate_video_wav
      SettingsJson:
        AudioDescriptions:
          - AudioTypeControl: FOLLOW_INPUT
            AudioSourceName: Audio Selector 1
            CodecSettings:
              Codec: WAV
              WavSettings:
                BitDepth: 16
                Channels: 2
                SampleRate: 44100
                Format: RIFF
            LanguageCodeControl: FOLLOW_INPUT
        ContainerSettings:
          Container: RAW
