AWSTemplateFormatVersion: 2010-09-09
Description: "Main template which will deploy infrastructure and services as nested\
  \ stacks.\n"
Parameters:
  AdapterRdsDbClass:
    Type: String
    Default: db.t3.small
    AllowedValues:
    - db.t3.small
    - db.t3.medium
    - db.t3.large
    - db.m5.large
    Description: The RDS Database class to use
  ApplicationTag:
    Type: String
    Default: accurate-video
    Description: Used to tag all resources
  CapacityProvider:
    Type: String
    Default: FARGATE
    AllowedValues:
    - FARGATE
    - FARGATE_SPOT
    Description: Capacity Provider
  ContainerRegistry:
    Type: String
    Description: Container Registry
    Default: 709825985650.dkr.ecr.us-east-1.amazonaws.com/codemill
  AdapterImageTag:
    Type: String
    Default: 4.6.1
    Description: Image tag
  AdapterContainerCpu:
    Type: String
    Default: '512'
    Description: Task CPU resources
  AdapterContainerMemory:
    Type: String
    Default: '1024'
    Description: Task memory resources
  AdapterDesiredCount:
    Type: Number
    Default: 1
    Description: Desired task count
  AnalyzeImageTag:
    Type: String
    Default: 4.6.1
    Description: Image tag
  AnalyzeContainerCpu:
    Type: String
    Default: '512'
    Description: Task CPU resources
  AnalyzeContainerMemory:
    Type: String
    Default: '1024'
    Description: Task memory resources
  AnalyzeDesiredCount:
    Type: Number
    Default: 1
    Description: Desired task count
  JobsImageTag:
    Type: String
    Default: 4.6.1
    Description: Image tag
  JobsContainerCpu:
    Type: String
    Default: '512'
    Description: Task CPU resources
  JobsContainerMemory:
    Type: String
    Default: '1024'
    Description: Task memory resources
  JobsDesiredCount:
    Type: Number
    Default: 1
    Description: Desired task count
  FrontendImageTag:
    Type: String
    Default: 4.6.1
    Description: Image tag
  FrontendContainerCpu:
    Type: String
    Default: '512'
    Description: Task CPU resources
  FrontendContainerMemory:
    Type: String
    Default: '1024'
    Description: Task memory resources
  FrontendDesiredCount:
    Type: Number
    Default: 1
    Description: Desired task count
  KeycloakImageTag:
    Type: String
    Default: 4.6.1
    Description: Image tag
  KeycloakContainerCpu:
    Type: String
    Default: '512'
    Description: Task CPU resources
  KeycloakContainerMemory:
    Type: String
    Default: '1024'
    Description: Task memory resources
  KeycloakDesiredCount:
    Type: Number
    Default: 1
    Description: Desired task count
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone Id
  KeycloakRdsDbClass:
    Type: String
    Default: db.t3.small
    AllowedValues:
    - db.t3.small
    - db.t3.medium
    - db.t3.large
    - db.m5.large
    Description: The RDS Database class to use
  DomainName:
    Type: String
    Description: Full domain name that will be given to the Accurate.Video Validate
      application (e.g. av.example.com)
  LogsRetention:
    Type: Number
    Default: 14
    Description: Number of days that application logs are saved in CloudWatch Logs
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Private Subnets which the ECS Services and RDS Database will
      be deployed in (At least two)
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Public Subnets which the Application Load Balancer will be deployed
      in (At least two)
  Vpc:
    Type: AWS::EC2::VPC::Id
    Description: The VPC which AccurateVideo will be deployed in
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network
      Parameters:
      - Vpc
      - PrivateSubnets
      - PublicSubnets
    - Label:
        default: DNS
      Parameters:
      - HostedZoneId
      - DomainName
    - Label:
        default: Docker Images
      Parameters:
      - AdapterImageTag
      - AnalyzeImageTag
      - FrontendImageTag
      - JobsImageTag
      - KeycloakImageTag
    - Label:
        default: Resources
      Parameters:
      - AdapterContainerCpu
      - AdapterContainerMemory
      - AdapterDesiredCount
      - AnalyzeContainerCpu
      - AnalyzeContainerMemory
      - AnalyzeDesiredCount
      - FrontendContainerCpu
      - FrontendContainerMemory
      - FrontendDesiredCount
      - JobsContainerCpu
      - JobsContainerMemory
      - JobsDesiredCount
      - KeycloakContainerCpu
      - KeycloakContainerMemory
      - KeycloakDesiredCount
    - Label:
        default: Database
      Parameters:
      - AdapterRdsDbClass
      - KeycloakRdsDbClass
    - Label:
        default: Other configuration
      Parameters:
      - ApplicationTag
      - CapacityProvider
      - LogsRetention
    ParameterLabels:
      AdapterRdsDbClass:
        default: Adapter Database Class
      ApplicationTag:
        default: Application Tag
      AdapterImageTag:
        default: Adapter Image Tag
      AnalyzeImageTag:
        default: Analyze Image Tag
      JobsImageTag:
        default: Jobs Image Tag
      FrontendImageTag:
        default: Frontend Image Tag
      KeycloakImageTag:
        default: Keycloak Image Tag
      AdapterContainerCpu:
        default: Adapter Container CPU
      AdapterContainerMemory:
        default: Adapter Container memory
      AdapterDesiredCount:
        default: Adapter Desired Count
      AnalyzeContainerCpu:
        default: Analyze Container Cpu
      AnalyzeContainerMemory:
        default: Analyze Container Memory
      AnalyzeDesiredCount:
        default: Analyze Desired Count
      FrontendContainerCpu:
        default: Frontend Container Cpu
      FrontendContainerMemory:
        default: Frontend Container Memory
      FrontendDesiredCount:
        default: Frontend Desired Count
      JobsContainerCpu:
        default: Jobs Container Cpu
      JobsContainerMemory:
        default: Jobs Container Memory
      JobsDesiredCount:
        default: Jobs Desired Count
      KeycloakContainerCpu:
        default: Keycloak Container Cpu
      KeycloakContainerMemory:
        default: Keycloak Container Memory
      KeycloakDesiredCount:
        default: Keycloak Desired Count
      CapacityProvider:
        default: Capacity Provider
      HostedZoneId:
        default: HostedZone ID
      KeycloakRdsDbClass:
        default: Keycloak Database Class
      DomainName:
        default: Domain Name
      LogsRetention:
        default: Application Logs Retention
      PrivateSubnets:
        default: Private Subnets
      PublicSubnets:
        default: Public Subnets
      Vpc:
        default: VPC ID
Mappings:
  Service:
    Adapter:
      ImageRepoName: accurate-video-adapter
      LoadbalancerListenerPriority: '2'
      LoadbalancerListenerPath: /api/*
      MultiAZ: 'false'
      RdsAllocatedStorage: '20'
      RdsMaxAllocatedStorage: '100'
    Analyze:
      ImageRepoName: accurate-video-analyze
      LoadbalancerListenerPath: /api/analyze/*
      LoadbalancerListenerPriority: '1'
    Frontend:
      ImageRepoName: accurate-video-frontend
      LoadbalancerListenerPath: '*'
      LoadbalancerListenerPriority: '4'
    Jobs:
      ImageRepoName: accurate-video-jobs
    Keycloak:
      ImageRepoName: accurate-video-keycloak
      LoadbalancerListenerPath: /auth*
      LoadbalancerListenerPriority: '3'
      MultiAZ: 'false'
      RdsAllocatedStorage: '20'
      RdsMaxAllocatedStorage: '21'
  Common:
    CloudFormation:
      Bucket: https://s3-eu-north-1.amazonaws.com/av-marketplace-cf/latest
    DNS:
      PrivateHostedZoneName: accurate-video.internal
Resources:
  LoadbalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ApplicationTag:
          Ref: ApplicationTag
        HostedZoneId:
          Ref: HostedZoneId
        DomainName:
          Ref: DomainName
        PublicSubnets:
          Fn::Join:
          - ','
          - Ref: PublicSubnets
        Vpc:
          Ref: Vpc
      TemplateURL: https://s3.eu-west-1.amazonaws.com/cftemplatesbucket-cloudformationbucket-3bbzz9kq4q2q/0693cab1d96a29c5da4a32449c2fe374.template
      TimeoutInMinutes: 30
  ClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ApplicationTag:
          Ref: ApplicationTag
      TemplateURL: https://s3.eu-west-1.amazonaws.com/cftemplatesbucket-cloudformationbucket-3bbzz9kq4q2q/d0474dfc15953cc2d36708e1e004578b.template
      TimeoutInMinutes: 30
  InfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ApplicationTag:
          Ref: ApplicationTag
        PrivateSubnets:
          Fn::Join:
          - ','
          - Ref: PrivateSubnets
        PublicLoadBalancerSecurityGroup:
          Fn::GetAtt:
          - LoadbalancerStack
          - Outputs.SecurityGroup
        Vpc:
          Ref: Vpc
        DBName: accurate_video
        DBUser: postgres
        DBClass:
          Ref: AdapterRdsDbClass
        DBAllocatedStorage: 5
      TemplateURL: https://s3.eu-west-1.amazonaws.com/cftemplatesbucket-cloudformationbucket-3bbzz9kq4q2q/f1b5ca11afbc14d41423472b8ae66c11.template
      TimeoutInMinutes: 30
Outputs:
  ApplicationURL:
    Description: Application URL
    Value:
      Fn::Sub: https://${DomainName}
